<%@ Page Title="" Language="C#" MasterPageFile="~/NewSite.Master" AutoEventWireup="true" CodeBehind="ListaProgramow.aspx.cs" Inherits="magisterka.ListaProgramow1" %>
<asp:Content ID="Content1" ContentPlaceHolderID="HeadContent" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="FeaturedContent" runat="server">
    <div class="left">
    <table>
        <tr>
            <td>
                <asp:Button ID="DodajProgram" runat="server" OnClick="DodajProgram_Click" Text="Dodaj program" Width="150px" CssClass="left" />
            </td>
        </tr>
        <tr>
            <td>
                <asp:Button ID="Archiwum" runat="server" OnClick="Archiwum_Click" Text="Archiwum" Width="150px" CssClass="left" />
            </td>
        </tr>
        <tr>
            <td>
                <asp:Label id="PoprAktual" runat="server" ForeColor="Green"></asp:Label>
            </td>
        </tr>
        <tr>
            <td>
                <%--AUT--%>
                <asp:GridView ID="GridViewProgramyAut" runat="server" AllowSorting="True" AutoGenerateColumns="False" 
                AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" AutoGenerateSelectButton="True" 
                CellPadding="10" DataSourceID="SqlDataSource2" ForeColor="#333333"
                OnRowEditing="GridViewProgramyAut_RowEditing" 
                OnRowUpdating="GridViewProgramyAut_RowUpdating" 
                OnRowDeleting="GridViewProgramyAut_RowDeleting"
                OnSelectedIndexChanged="GridViewProgramyAut_SelectedIndexChanged" CaptionAlign="Top" HorizontalAlign="Center" EmptyDataText="Brak danych do wyświetlenia" DataKeyNames="id_projektu" Caption="PROGRAMY AUTORSKIE" CssClass="GridViewEditRow">
                <AlternatingRowStyle BackColor="White" />
                <Columns>   <%--boundfield nie ma możliwości zmiany na multilines w editmode, tylko templates mogą--%>
                    <asp:BoundField DataField="id_projektu" HeaderText="id_projektu" SortExpression="id_projektu" InsertVisible="False" ReadOnly="True" Visible="False" />
                    <asp:BoundField DataField="nazwa_projektu" HeaderText="nazwa" SortExpression="nazwa_projektu" NullDisplayText="--" />
                    <asp:BoundField DataField="streszczenie" HeaderText="streszczenie" SortExpression="streszczenie" ItemStyle-Wrap="True" ApplyFormatInEditMode="False" ValidateRequestMode="Inherit" NullDisplayText="--" >
                <ItemStyle Wrap="True"></ItemStyle>
                    </asp:BoundField>
                    <asp:BoundField DataField="id_Admin" HeaderText="Admin" SortExpression="id_Admin" Visible="False" />
                </Columns>
                <EditRowStyle CssClass="GridViewEditRow" BackColor="#2461BF" BorderColor="Red" BorderStyle="Solid" BorderWidth="1px" />
                <FooterStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" BorderColor="Yellow" BorderStyle="Solid" BorderWidth="1px" HorizontalAlign="Center" VerticalAlign="Middle" />
                <HeaderStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" BorderColor="Black" BorderStyle="Solid" BorderWidth="1px" HorizontalAlign="Justify" VerticalAlign="Middle" />
                <PagerStyle BackColor="#2461BF" ForeColor="White" HorizontalAlign="Center" />
                <RowStyle BackColor="#EFF3FB" BorderColor="Black" BorderStyle="Solid" BorderWidth="1px" HorizontalAlign="Center" VerticalAlign="Middle" />
                <SelectedRowStyle BackColor="#D1DDF1" Font-Bold="True" ForeColor="#333333" />
                <SortedAscendingCellStyle BackColor="#F5F7FB" />
                <SortedAscendingHeaderStyle BackColor="#6D95E1" />
                <SortedDescendingCellStyle BackColor="#E9EBEF" />
                <SortedDescendingHeaderStyle BackColor="#4870BE" />
                </asp:GridView>
        <%--            <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:baza_pacjentow_v2ConnectionString %>" 
                        SelectCommand="SELECT PROJEKT.id_projektu, PROJEKT.nazwa_projektu, PROJEKT.streszczenie PROJEKT.id_Admin FROM [PROJEKT] WHERE ([id_Admin] = @id_uzytk) AND status_archiwum = 'False'">
                        <SelectParameters>
                            <asp:SessionParameter DefaultValue="-1" Name="id_uzytk" SessionField="id_uzytk" />
                        </SelectParameters>
                    </asp:SqlDataSource>
                <%--DeleteCommand - trzeba zmienić status_archiwum --%>
                <asp:SqlDataSource ID="SqlDataSource2" runat="server" ConnectionString="<%$ ConnectionStrings:baza_pacjentow_v2ConnectionString %>" 
                    SelectCommand="SELECT [id_projektu], [nazwa_projektu], [streszczenie], [id_Admin] FROM [PROJEKT] WHERE ([id_Admin] = @id_uzytk) AND status_archiwum = 'False'"
                    UpdateCommand="UPDATE [dbo].[PROJEKT] SET [nazwa_projektu]=@nazwa_projektu, [streszczenie]=@streszczenie WHERE [id_projektu] = @id_projektu"
                    DeleteCommand="UPDATE [dbo].[PROJEKT] SET [status_archiwum]='True' WHERE [id_projektu] = @id_projektu"
                    OnDeleted="Aktualizacja" OnUpdated="Aktualizacja">
                    <SelectParameters>
                        <asp:SessionParameter DefaultValue="-1" Name="id_uzytk" SessionField="id_uzytk" />
                    </SelectParameters>
                </asp:SqlDataSource>
            </td>
            <td>
                <%--KOOP--%>
                <asp:GridView ID="GridViewProgramyKoop" runat="server" AllowSorting="True" AutoGenerateColumns="False" 
                AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" AutoGenerateSelectButton="True" 
                CellPadding="10" DataSourceID="SqlDataSource3" ForeColor="#333333"
                OnRowEditing="GridViewProgramyKoop_RowEditing" OnRowUpdating="GridViewProgramyKoop_RowUpdating" OnRowDeleting="GridViewProgramyKoop_RowDeleting"
                OnSelectedIndexChanged="GridViewProgramyKoop_SelectedIndexChanged" CaptionAlign="Top" HorizontalAlign="Center" EmptyDataText="Brak danych do wyświetlenia" DataKeyNames="id_projektu" PagerSettings-Position="Top" Caption="PROGRAMY KOOPERATORSKIE ">
                <AlternatingRowStyle BackColor="White" />
                <Columns>
                    <asp:BoundField DataField="id_projektu" HeaderText="id_projektu" SortExpression="id_projektu" InsertVisible="False" ReadOnly="True" Visible="False" />
                    <asp:BoundField DataField="nazwa_projektu" HeaderText="nazwa" SortExpression="nazwa_projektu" NullDisplayText="--" />
                    <asp:BoundField DataField="streszczenie" HeaderText="streszczenie" SortExpression="streszczenie" NullDisplayText="--" />
                    <asp:BoundField DataField="id_Admin" HeaderText="id_Admin" SortExpression="id_Admin" Visible="False" />
                    <asp:BoundField DataField="login" HeaderText="Admin" SortExpression="login" NullDisplayText="--" />
                </Columns>
                <EditRowStyle CssClass="GridViewEditRow" BackColor="#2461BF" BorderColor="Red" BorderStyle="Solid" BorderWidth="1px" Height="40px" />
                <FooterStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" BorderColor="Yellow" BorderStyle="Solid" BorderWidth="1px" HorizontalAlign="Justify" VerticalAlign="Middle" />
                <HeaderStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" BorderColor="Black" BorderStyle="Solid" BorderWidth="1px" HorizontalAlign="Justify" VerticalAlign="Middle" />

                <PagerSettings Position="Top"></PagerSettings>

                <PagerStyle BackColor="#2461BF" ForeColor="White" HorizontalAlign="Center" />
                <RowStyle BackColor="#EFF3FB" BorderColor="Black" BorderStyle="Solid" BorderWidth="1px" HorizontalAlign="Center" VerticalAlign="Middle" />
                <SelectedRowStyle BackColor="#D1DDF1" Font-Bold="True" ForeColor="#333333" />
                <SortedAscendingCellStyle BackColor="#F5F7FB" />
                <SortedAscendingHeaderStyle BackColor="#6D95E1" />
                <SortedDescendingCellStyle BackColor="#E9EBEF" />
                <SortedDescendingHeaderStyle BackColor="#4870BE" />
                </asp:GridView>
                <asp:SqlDataSource ID="SqlDataSource3" runat="server" ConnectionString="<%$ ConnectionStrings:baza_pacjentow_v2ConnectionString %>" 
                    SelectCommand="SELECT PROJEKT.id_projektu, [nazwa_projektu],[streszczenie], id_Admin, [dbo].[UZYTK].login FROM [dbo].[PROJEKT] JOIN [dbo].[UZYTK] ON PROJEKT.id_Admin = [dbo].[UZYTK].id_uzytk JOIN [UZYTK_PROJEKT] ON PROJEKT.id_projektu = UZYTK_PROJEKT.id_projektu WHERE (UZYTK_PROJEKT.id_uzytk = @id_uzytk) AND status_archiwum = 'False'"
                    UpdateCommand="UPDATE [dbo].[PROJEKT] SET [nazwa_projektu]=@nazwa_projektu, [streszczenie]=@streszczenie WHERE [id_projektu] = @id_projektu"
                    DeleteCommand="UPDATE [dbo].[PROJEKT] SET [status_archiwum]='True' WHERE [id_projektu] = @id_projektu"
                    OnDeleted="Aktualizacja" OnUpdated="Aktualizacja">
                    <DeleteParameters>
                        <asp:Parameter Name="id_projektu" />
                    </DeleteParameters>
                    <SelectParameters>
                        <asp:SessionParameter DefaultValue="-1" Name="id_uzytk" SessionField="id_uzytk" />
                    </SelectParameters>
                    <UpdateParameters>
                        <asp:Parameter Name="nazwa_projektu" />
                        <asp:Parameter Name="streszczenie" />
                        <asp:Parameter Name="id_projektu" />
                    </UpdateParameters>
                </asp:SqlDataSource>
            </td>
        </tr>
    </table>
    </div>
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="MainContent" runat="server">
</asp:Content>
